# Generated by Django 5.2.5 on 2025-08-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surahName', models.CharField(max_length=30)),
                ('Reciter', models.CharField(max_length=100)),
                ('reciterImage', models.ImageField(default='', upload_to='main_app/static/uploads/picutres')),
                ('audio', models.FileField(upload_to='main_app/static/uploads/audio')),
            ],
        ),
    ]
