# Generated by Django 5.2.5 on 2025-08-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recitation',
            name='reciterImage',
            field=models.ImageField(default='', upload_to='main_app/static/uploads/pictures'),
        ),
    ]
