# Generated by Django 5.2.5 on 2025-08-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_recitation_reciterimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitation',
            name='approval',
            field=models.BooleanField(default=False),
        ),
    ]
