# Generated by Django 5.2.5 on 2025-09-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_recitation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recitation',
            name='approval',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='Pending'),
        ),
        migrations.AlterField(
            model_name='recitation',
            name='reciterImage',
            field=models.ImageField(default='main_app/static/uploads/pictures/default.jpeg', upload_to='main_app/static/uploads/pictures'),
        ),
    ]
