# Generated by Django 5.2.5 on 2025-09-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_recitation_approval_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recitation',
            name='approval',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING'),
        ),
    ]
