# Generated by Django 5.2.5 on 2025-09-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_recitation_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='recitation',
            name='description',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
