# Generated by Django 5.2.5 on 2025-09-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_recitation_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recitation',
            name='description',
            field=models.TextField(max_length=1000),
        ),
    ]
